---
title: "Useful Title"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options:
  chunk_output_type: inline
---

 

```{r}
plot(cars)
```
#Part 1
```{r}
install.packages("xtable")
```

```{r}
library(tidyverse)
```

```{r}
anscombe
```

```{r}
ansc <-
  bind_cols(
  anscombe %>% 
    select(matches("x")) %>% 
    gather(dataset, "x"),
  anscombe %>%
    select(matches("y")) %>% 
    gather(key, "y")
) %>% 
select(-key) %>% 
  mutate(dataset=gsub("x", "", dataset)) %>% 
  as_tibble()
```
```{r}
ansc
```

```{r}
ansc %>% 
  group_by(dataset) %>% 
  summarize(
    mean_x = mean(x),
    stdev_x = sd(x),
    mean_y = mean(sd), 
    stdev_y = sd(y)
  )
```

```{r}
ansc %>% ggplot(aes(x, y, color = dataset)) +
  geom_point() +
  facet_wrap(~dataset, ncol = 2)
```
#part 2

```{r}
library(xtable)
library(knitr)
```

```{r}
install.packages("xtable", repos="http://R-Forge.R-project.org")
```

```{r}
head(iris)
```
```{r}
kable(head(iris))
  align= c("l", "c", "r", "c", "l")
  colnames = c("Sepal Length", "Sepal Width", "Sepal Length", "Sepal Width", "Species")

```

```{r}
head(airquality)
```

```{r}
kable(head(airquality))
  align= c("r", "r", "c", "c", "l", "l")
  colnames = c("Ozone(ppb)", "Solar R(lang)", "Wind(mph)", "Temp(F)", "Month", "Day")
```

```{r}
head(chickwts)
```

```{r}
chicks_lm <- lm(weight ~ feed, data = chickwts)

summary(chicks_lm)
```

```{r}
kable(chicks_lm)
```
Knitr can't extract the data because of the 'lm' title. I need another way to get in to the data.

```{r}
xtable(chicks_lm) %>% kable()
```

```{r}
trees
```

```{r}
girth_lm <- lm(Girth ~ Height, data = trees)
girth_lm
xtable(girth_lm) %>% kable()
```

$e = mc^2$
$$\frac{\Delta N}{\Delta t} = rn\left(\frac{K-N}{K}\right).$$
$$V^0 = \frac{V^m[S]}{(K^m + [S])}$$

$$\chi^2 = \frac{(O-E)^2}{E}$$

