---
title: "Hw03"
author: "Molly"
date: "12/20/2018"
output: html_document
---

```{r}
install.packages("gapminder")
```

```{r}
library("gapminder")


aggregate(lifeExp ~ continent, gapminder, median)

```

```{r}
library("dplyr")
gapminder %>% 
  filter(year == 2007) %>% 
  group_by(continent) %>% 
  summarise(lifeExp = median(lifeExp))
```

```{r}
library("ggplot2")
ggplot(gapminder, aes(x = continent, y = lifeExp)) +
  geom_boxplot(outlier.colour = "hotpink") +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4)
```

#everything is officially downloaded, moving to assignnment

```{r}
library("dplyr")
gapminder %>% 
  group_by(continent) %>% 
  summarise(gdpPercap = max(gdpPercap))

```

```{r}
library("dplyr")
gapminder %>% 
  group_by(continent) %>% 
  summarise(gdpPercap = min(gdpPercap))
```

```{r}
library("ggplot2")
ggplot(gapminder, aes(x = continent, y = gdpPercap)) +
  geom_boxplot(outlier.color = "blue") +
  geom_jitter(position = position_jitter(width = 0.1, height =1))


```


```{r}
library(dplyr)
gapminder %>% 
  filter(continent  %in% "Africa") %>% 
  group_by(year) %>% 
  summarise(pop = mean(pop)) 


```

```{r}
library(dplyr)
gapminder %>% 
  filter(continent %in% "Asia") %>% 
  group_by(year) %>% 
  summarise(lifeExp = mean(lifeExp))
```


```{r}
library("ggplot2")
ggplot(subset(gapminder, continent != "Asia"),
       aes(x = year, y = lifeExp)) +
  geom_count(inherit.aes = TRUE)
```

