---
title: "HW 07: Data Visualisation"
author: "Molly Brakhane"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
#Installation
```{r}
library(tidyverse)
install.packages("GGally")
install.packages("devtools")
```
```{r}
library(patchwork)
library(GGally)
```

# Part 1
## Import and Wrangle
```{r}
sparrows
sparrows_a <- sparrows %>% 
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))
sparrows_a
```
## Figure 2: Outliers
```{r}
plot_box <- sparrows_a %>% 
  ggplot(aes(x = box_group,
             y = wingcrd)) +
  geom_boxplot(width = 0.25) +
  labs(x = NULL,
       y = "Wing length (mm)"
       )
```
```{r}
plot_cleveland <- sparrows_a %>% 
  ggplot(aes(x = wingcrd,
             y = row_order)) +
  geom_point() +
  labs(x = "Wing length (mm)",
       y = "Order of the Data")
```
```{r}
plot_cleveland + plot_box

```
```{r}
plot_box + plot_cleveland + coord_flip()

```

## Figure 3: outliers
```{r}
p_culmen <- sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = culmen)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_culmen
p_nalospi <- sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = nalospi)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wt <-sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_line(aes(x = wt)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wingcrd <- sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wingcrd)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_tarsus <-  sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = tarsus)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_head <- sparrows_a %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = head)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```
```{r}
p_culmen + p_nalospi + p_wt + p_wingcrd + p_tarsus + p_head
```
Head, Tarsus, and Nalopsi have outlier data.


## Figure 5: Distribution
```{r}
h1 <- sparrows_a %>% 
  filter(Month %in% 6:8) %>% 
  ggplot() +
  geom_histogram(aes(x = wt),
                 binwidth = 0.5,
                 boundary = 0,
                 closed = "right",
                 color = "black") +
  scale_x_continuous(breaks = seq(14, 28, by = 2))
h2 <- sparrows_a %>% 
  filter(Month %in% 6:8) %>% 
  mutate(Month = case_when(
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August")) %>% 
  ggplot() +
  geom_histogram(aes(x=wt),
                 binwidth = 0.5,
                 boundary = 0,
                 color = "black") +
  scale_x_continuous(breaks = seq(14, 28, by = 2)) +
  facet_wrap(~ Month, ncol = 1)
```
```{r}
h1 + h2
```
## Grad and Honors
```{r}
h1 <- sparrows_a %>% 
  filter(Month %in% 6:8) %>% 
  ggplot() +
  geom_density(aes(x = wt)) +
  scale_x_continuous(breaks = seq(14, 28, by = 2))
h2 <- sparrows_a %>% 
  filter(Month %in% 6:8) %>% 
  mutate(Month = case_when(
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August")) %>% 
  ggplot() +
  geom_density(aes(x = wt, fill = Month)) +
  scale_x_continuous(breaks = seq(14, 28, by = 2))
```
```{r}
h1 + h2
```

## Figure 10: Relationships
```{r}
sparrows_a %>% ggscatmat(columns = 1:7)
```
THATS CRAZY

## Figure 11: Interactions
```{r}
month_order = c("May", "June", "July", "August", "September")
sparrows_a %>% 
  filter(Month %in% 5:9,
         Sex !=0) %>% 
  mutate(Month = case_when(
    Month == 5 ~ "May",
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August",
    Month == 9 ~ "Septermber"),
    Month = factor(Month, levels = month_order, ordered = TRUE),
    Sex = ifelse(Sex == 4, "Male", "Female")) %>% 
  ggplot(aes(x = wingcrd,
             y = wt)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_grid(Sex ~ Month)
```



# Part 2 :; Aegla Crabs

```{r}
aegla_crabs_raw
```
```{r}
aegla_crabs <- aegla_crabs_raw %>% 
  select(-c("Site", "AT", "WT", "Shrimp", "Aeglam", "AeglaFe", "AeglaFo")) %>% 
  drop_na(c("N")) %>% 
  mutate(row_order = 1:nrow(.))
aegla_crabs
```
## Cleveland Plots
```{r}
c1 <- ggplot(data = aegla_crabs, aes(y = row_order)) +
  geom_point(aes(x = Width)) +
  labs(y = "Order of Data")
c2 <- ggplot(data = aegla_crabs) +
  geom_point(aes(x = Flow, y = row_order)) +
  labs(y = "Order of Data")
c3 <- ggplot(data = aegla_crabs) +
  geom_point(aes(x = Cond, y = row_order)) +
  labs(y = "Order of Data")
c4 <- ggplot(data = aegla_crabs) +
  geom_point(aes(x = pH, y = row_order)) +
  labs(y = "Order of Data")
c1 + c2 + c3 + c4
```

## Histograms
```{r}
h1 <- ggplot(data = aegla_crabs) +
  geom_histogram(aes(x = pH),
                 binwidth = .05,
                 boundary = 0,
                 closed = "left",
                 color = "black")
h1
```
```{r}
h2 <-  ggplot(data = aegla_crabs) +
  geom_histogram(aes(x = Crab),
                 binwidth = 1,
                 boundary = 0,
                 closed = "left",
                 color = "black")
h2
```
```{r}
h3 <-  ggplot(data = aegla_crabs) +
  geom_histogram(aes(x = Depth),
                 binwidth = .5,
                 boundary = 1,
                 closed = "left",
                 color = "black")
h3
```
## Density Plots
```{r}
d1 <- ggplot(data = aegla_crabs) +
  geom_density( aes(x = pH))
d1
```
```{r}
d2 <- ggplot(data = aegla_crabs) +
  geom_density( aes(x = Crab))
d2
```
```{r}
d3 <- ggplot(data = aegla_crabs) +
  geom_density( aes(x = Depth))
d3
```
## Patchwork
```{r}
h1 + d1 + h2 + d2 + h3 + d3 + plot_layout(ncol = 2, nrow = 3)
```


## GGPpairs
```{r}
aegla_crabs %>% ggpairs(columns = 1:13)
```







