---
title: "HW 06 Part 2: Wrangling II"
author: "Molly Brakhane"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(knitr)
library(smatr)
```


# Darters in Riffles
```{r}
read.delim("~/Masters/GABD/brakhane_molly/Data/darter.txt")
```



```{r}
start_pos <- c(1, 4, 15, 16, 17, 18, 21, 25, 29, 33, 36, 39, 40)
stop_pos <- c(3, 14, 15, 16, 17, 20, 24, 28, 32, 35, 38, 40, 41)
names <- c("Specimen ID", "Species", "Riffle", "Age", "Sex", "Length", "Depth", "Velocity", "Temperature", "MajSub", "MinSub", "MajType", "MinType")
darters <- read.fwf("~/Masters/GABD/brakhane_molly/Data/darter.txt", skip = 15, widths = c(3, 11, 1, 1, 1, 3, 4, 3, 3, 2, 2, 1, 1), col.names = names)
darters
```
## Wrangle Data
```{r}
 
darters_b <- filter(darters, !Species %in% c("tetrazonum", "zonale"))
darters_c <- mutate(darters_b,
  total_substrate = MajSub + MinSub,
         Length = Length * 10,
         Riffle = recode(Riffle, "1" = "Riffle 1", "2" = "Riffle 2"),
         Sex = recode(Sex, "m" = "Male", "f" = "Female"),
  )
darters_c
```
## Summarize Data
```{r}
summary_darter <- darters_c %>% 
  group_by(Riffle, Species) %>% 
  summarise(average_length = mean(Length, na.rm = TRUE),
            average_depth = mean(Depth, na.rm = TRUE),
            average_velocity = mean(Velocity, na.rm = TRUE))
summary_darter
```
## Table Results
```{r}
ggplot(data = summary_darter) +
  geom_point(mapping = aes(x = average_velocity, y = average_depth, size = average_length, color = Species)) +
  facet_wrap(~Riffle, nrow = 2)
```

## Plot 1
```{r}
ggplot(data = darters_c) +
  stat_summary(mapping = aes(x = Species, y = Length),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  ) +
  geom_point(data = summary_darter, 
             mapping = aes(x = Species, y = average_length), shape = 22, fill = "black")+
  coord_flip() +
  facet_wrap(~Riffle, nrow = 2) +
  labs(y = "Length (mm)", x = NULL)
```
Riffle 2 has a much larger distribution of sizes than Riffle 1.
## Plot 2
```{r}
ggplot(data = darters_c) +
  stat_summary(data = summary_darter,
  mapping = aes(x = Species, y = average_length), 
  fun.y = mean,
  geom = "point",
  size = 3, 
  shape = 15, 
  color = "maroon") +
  geom_point(mapping = aes(x = Species, y = Length), color = "gray70") +
  stat_summary(
    mapping = aes(x = Species, y = Length),
    fun.y = median,
    geom = "point",
    size = 2.2) +
  facet_wrap(~Riffle, nrow = 2) +
  labs(y = "Length(mm)", x = NULL) +
  coord_flip()
```
The average is odd compared to the data sets. I must have messed up but I don't know how. D:


# Stress and Corticosterones in Birds
## Import Data
```{r}
library(tidyverse)
library(smatr)
library(knitr)
library(dplyr)
names <- c("capture_date", "day", "site", "urban_score", "cortF", "cortB", "sex", "smi", "tarsus", "mass", "basal_cort", "stress_cort")
feathers <- read.csv("~/Masters/GABD/brakhane_molly/Data/feathers.csv", dec = ",")
# I cannor get locale = locale(decimal_mark = ",") to work for the life of me. I could get dec = "," to work. And I could get the file imported with the correct decimal mark two different ways, just not with locale
feathers <- feathers %>% 
  `colnames<-`(names)
feathers
```
/crying
## Wrangle Data
```{r}
mean_tarsus <- mean(feathers$tarsus, na.rm = TRUE)

```
```{r}
feathers_b <-  mutate(feathers, log_mass = log(mass), log_tarsus = log(tarsus))
```

```{r}
?sma
major_axis <- sma(log_mass~log_tarsus, data = feathers_b)
summary(major_axis)
coef(major_axis)
```
```{r}
b <- coef(major_axis)["slope"]
feathers_smi<- feathers %>% 
  mutate(
    new_smi = mass * (mean_tarsus/tarsus)^b)
feathers_smi %>% 
  select(smi, new_smi)
feathers_smi
```
 
## Summarize Data
```{r}
summary_feathers <- feathers_smi %>% 
  group_by(site) %>% 
  summarize(average_basal = mean(basal_cort, na.rm = TRUE),
            se_basal = sd(basal_cort, na.rm = TRUE) / sqrt(n()))
summary_feathers

```

## Graph Data
*Plot 1*
```{r}
ggplot(data = feathers_smi) +
  geom_boxplot(mapping = aes(x = site, y = new_smi))
```

*Plot 2*
```{R}
ggplot() +
  geom_point(data = feathers_smi, aes(x = site, y = basal_cort)) +
  geom_errorbar(data = summary_feathers, aes(x = site, ymin = average_basal - se_basal, ymax =  average_basal + se_basal))
```
 
*Plot 3*
```{r}
stress_summary <- feathers_smi %>% 
  group_by(site) %>% 
  mutate(
    avg_stress = mean(stress_cort, na.rm = TRUE),
    se_cort = sd(stress_cort, na.rm = TRUE)/sqrt(NROW(feathers_smi)))
ggplot() +
  geom_point(data = feathers_smi, aes(x = site, y = stress_cort)) +
  geom_linerange(data = stress_summary, aes(x = site, ymin = avg_stress - se_cort, ymax = avg_stress + se_cort))
```

## Graduate and Honors Students

```{r}
ggplot() +
  geom_point(data = feathers_smi, aes(x = site, y = stress_cort)) +
  stat_summary(data = feathers_smi,
    mapping = aes(x = site, y = stress_cort),
    fun.y = median,
    geom = "point",
    size = 3,
    color = "maroon")
  geom_linerange(data = stress_summary, aes(x = site, ymin = ymin, ymax = ymax)) 
  
```

```{r}
ggplot() +
  geom_point(data = feathers_smi, aes(x = site, y = basal_cort)) +
  geom_errorbar(data = edit_summary, aes(x = site, ymin = ymin, ymax = ymax), size = 0.3)
```

